"""
build_skills_matrix.py — Generate the definitive Antigravity Agent Skills Matrix.
Only scans .agent/skills/ (the official 59 agents). Writes to SKILLS_MATRIX.md.

Usage: python execution/build_skills_matrix.py
"""

import re
from pathlib import Path
from datetime import date

ROOT = Path(__file__).parent.parent
SKILLS_DIR = ROOT / ".agent" / "skills"
OUTPUT = ROOT / "SKILLS_MATRIX.md"

REQUIRED = [
    "The Creed", "Identity", "Personality", "Capabilities",
    "Standard Operating Procedures", "Collaboration", "Feedback Loop",
    "Performance Metrics", "Restrictions", "Learning Log", "Tools & Resources"
]

def parse_agent(agent_dir: Path) -> dict:
    sf = agent_dir / "SKILL.md"
    if not sf.exists():
        return None
    content = sf.read_text(encoding="utf-8")
    handle = agent_dir.name

    tier_match = re.search(r'^tier:\s*(.+)', content, re.MULTILINE)
    tier = tier_match.group(1).strip() if tier_match else "Uncategorized"

    desc_match = re.search(r'^description:\s*(.+)', content, re.MULTILINE)
    desc = desc_match.group(1).strip() if desc_match else "-"

    name_match = re.search(r'\*\*Human Name\*\*\s*\|\s*([^|\n]+)', content)
    name = name_match.group(1).strip() if name_match else handle.title()

    nick_match = re.search(r'\*\*Nickname\*\*\s*\|\s*([^|\n]+)', content)
    raw_nick = nick_match.group(1).strip() if nick_match else "-"
    nickname = raw_nick.strip('"').strip("_")

    role_match = re.search(r'\*\*Role\*\*\s*\|\s*([^|\n]+)', content)
    role = role_match.group(1).strip() if role_match else desc

    score = sum(1 for s in REQUIRED if f"## {s}" in content)

    return {
        "handle": handle,
        "tier": tier,
        "name": name,
        "nickname": nickname,
        "role": role,
        "score": score,
        "perfect": score == 11,
    }


def build_matrix():
    agents = []
    for agent_dir in sorted(SKILLS_DIR.iterdir()):
        if agent_dir.is_dir() and agent_dir.name != "methodology":
            data = parse_agent(agent_dir)
            if data:
                agents.append(data)

    # Group by tier
    tiers = {}
    for a in agents:
        tiers.setdefault(a["tier"], []).append(a)

    total = len(agents)
    perfect = sum(1 for a in agents if a["perfect"])

    lines = [
        "# Antigravity Agent Skills Matrix",
        "",
        f"> **Generated:** {date.today()} | **Jai.OS 5.0** | **Shared Brain:** ONLINE",
        f"> **Orchestra Size:** {total} agents | **11/11 Compliant:** {perfect}/{total}",
        "",
        "---",
        "",
    ]

    # Summary table
    lines.append("## Summary by Tier\n")
    lines.append("| Tier | Agents | 11/11 Complete |")
    lines.append("| :--- | :----- | :------------- |")
    for tier in sorted(tiers.keys()):
        tier_agents = tiers[tier]
        tier_perfect = sum(1 for a in tier_agents if a["perfect"])
        lines.append(f"| {tier} | {len(tier_agents)} | {tier_perfect}/{len(tier_agents)} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-tier agent tables
    for tier in sorted(tiers.keys()):
        tier_agents = sorted(tiers[tier], key=lambda a: a["handle"])
        lines.append(f"## {tier}\n")
        lines.append("| Handle | Human Name | Nickname | Role | Score |")
        lines.append("| :----- | :--------- | :------- | :--- | :---- |")
        for a in tier_agents:
            status = "✅ 11/11" if a["perfect"] else f"⚠️ {a['score']}/11"
            lines.append(f"| @{a['handle']} | {a['name']} | {a['nickname']} | {a['role']} | {status} |")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Jai.OS 5.0 | The Antigravity Orchestra | Auto-generated by `execution/build_skills_matrix.py`_")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"SKILLS_MATRIX.md written — {total} agents, {perfect}/{total} at 11/11")

    # Print any non-perfect agents
    if perfect < total:
        print("\nAgents needing attention:")
        for a in agents:
            if not a["perfect"]:
                print(f"  @{a['handle']} ({a['score']}/11)")


if __name__ == "__main__":
    build_matrix()
